version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-fipe-app-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
